name: Upload release assets

# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docs/canboat.json
            docs/canboat.xml
            docs/canboat.xsd